spring.datasource.url=jdbc:h2:mem:autoescola;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=sa
spring.flyway.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
